<?php get_header(); ?>
	<img class="[ absolute ][ width--50 ][ margin-left--25p ][ z-index---1 ]" src="<?php echo THEMEPATH; ?>images/spining-elements.png" alt="imagen spining elements">
	<h2 class="[ color-primary ][ text-center ]">Aviso de privacidad</h2>
	<div class="[ text-center ][ margin-bottom--large margin-auto ][ width--900p ]">
		<div class="[ border-bottom--primary border-top--primary ][ padding-top--large padding-bottom--large ]" data-parsley-validate>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac purus vitae velit suscipit iaculis sed vitae nisl. Duis elit neque, convallis vitae nunc quis, efficitur dictum odio. Etiam condimentum sem at nulla finibus vehicula. Pellentesque commodo est ut enim efficitur, in interdum nulla luctus. Donec mauris sem, blandit at quam non, tincidunt luctus velit. Nullam auctor in ligula ac vestibulum. Nunc sodales tempus elit nec dictum. Suspendisse sodales vulputate ante. Praesent volutpat ac neque sit amet efficitur. Etiam viverra dui arcu, in congue tellus venenatis a. Morbi ac hendrerit justo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus quis neque et sapien feugiat feugiat.</p>
			<p>Pellentesque vitae ipsum viverra nisi ullamcorper pellentesque. Donec semper dignissim metus vitae tincidunt. Nam consequat sem quis nisi fringilla posuere. Donec blandit quam a odio rhoncus, vel venenatis nulla hendrerit. Ut quis facilisis arcu. Morbi lectus augue, pulvinar sit amet pellentesque dapibus, porta eget mi. Nullam in consequat velit. Nullam accumsan ante sed fermentum aliquet. Cras ac enim ut sem pellentesque facilisis. Quisque viverra, libero ac vestibulum pretium, diam tortor elementum lorem, eget pulvinar nisi sem eu tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dictum augue non risus ornare, id vehicula lorem commodo. Mauris ornare est sit amet risus porttitor pulvinar. Vivamus suscipit, est vitae placerat sagittis, ligula leo fermentum lectus, eget gravida sem felis a diam. Sed dictum imperdiet ornare.</p>
			<p>Aenean a aliquam orci, non tempus nisl. Mauris vitae bibendum nibh. Praesent non purus ac diam dictum dapibus. Curabitur nec interdum mauris. In et ultricies ligula. Aliquam ex ex, placerat eu lorem ac, fermentum fermentum orci. Nam et sem at lorem condimentum finibus. Donec ornare, ante sit amet varius lacinia, ligula nisi convallis magna, ut cursus odio orci in urna. Donec tortor turpis, venenatis non consectetur sit amet, placerat tempor nulla. Sed viverra venenatis leo et sollicitudin. Donec tristique ante eget eros lacinia egestas. Pellentesque tellus elit, sagittis vitae velit nec, iaculis varius lectus. Duis at hendrerit nunc, sed aliquam nunc. Ut vel lectus purus. Suspendisse id malesuada augue.</p>
			<p>Nam vitae arcu ut tortor congue cursus. Nam dignissim lobortis dignissim. Etiam tristique sit amet ante nec consequat. Aliquam vitae velit massa. Nullam pulvinar, sapien in tempus feugiat, nunc tellus elementum magna, quis congue est sapien ac nunc. Nunc in ante fermentum, sollicitudin ligula eget, lacinia est. Sed ornare pretium vulputate. Mauris malesuada eros magna, ac condimentum enim aliquet interdum. Sed finibus magna nec elit sagittis, et lobortis tellus accumsan. Nulla ut orci faucibus, hendrerit urna eu, commodo nunc. Vestibulum vel pharetra quam. Quisque id massa nibh. Maecenas eu nisl eget enim egestas ultrices ut at tortor. Integer facilisis libero sem, sed posuere eros consequat a.</p>
		</div>
	</div>
	<div class="[ text-center ][ margin-bottom--large ]">
		<div class="[ border-primary border-radius--20 ][ inline-block ]">
			<a href="<?php echo site_url('/registro'); ?>" class="[ inline-block ][ btn btn--primary ][ text-center ][ margin-auto ]">VOLVER</a>
		</div>
	</div>
<?php get_footer(); ?>